services:
  - type: web
    name: pan-card-tampering
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 60
    envVars:
      - key: SECRET_KEY
        generateValue: true
